//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodStock
    {
        public int ID { get; set; }
        public string BloodType { get; set; }
        public int bloodQuantityID { get; set; }
    
        public virtual NewDonor NewDonor { get; set; }
    }
}
